### ISSUE TITLE
Turn off an alignment

### ISSUE THREAD

**Issue by nedzadarek** [markandgo/text.lua#2]
How can we turn off the alignment? I see only 3 options (left, right, center).  
For example, I have text like this:
```
bla
   bla
      bla
```
but it display it incorectly as:
```
bla
bla
bla
```

**Comment by markandgo** [comment]
I have chosen to strip the leading and trailing spaces in the current version because of code limitations to make wrapping and aligning work correctly. I have no plan at the moment to change this. You can simulate a leading (or trailing) space on each line by using a blank custom tag with a specific width.

For example:

````lua
mytext = '<space4>line<space4>'

tags = {
	space4 = {
		draw   = function() end,
		width  = 4,    
		length = 4,
	},
}
````
